version: '3.4'
services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    ports:
      - 5432:5432
    # volumes:
    #   - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: video
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: root
  ms-api:
    build: .
    container_name: ms-api
    ports:
      - 8080:8080
    depends_on:
      - postgresql
    volumes:
      - ./logs:/go/src/ms-api/logs
      - ./assets:/go/src/ms-api/assets
    hostname: ms-api
    restart: always
    user: root
