apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-api-nginx-conf
data:
  nginx.conf: |
    server {
        listen 80;

        location /api/v1/videos/upload {
            proxy_pass http://127.0.0.1:8080/api/v1/videos/upload;
            proxy_redirect off;
            client_max_body_size 50m;
            client_body_buffer_size 50m;
        }
        location / {
            proxy_pass http://127.0.0.1:8080;
            proxy_redirect off;
        }
    }
